# Generated by Django 5.1.5 on 2025-01-25 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('additional_data', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('company', 'شركة'), ('institution', 'مؤسسة'), ('individual', 'فرد')], max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('id_issue_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('id_copy', models.FileField(upload_to='tenants/id/')),
                ('postal_number_copy', models.FileField(upload_to='tenants/postal/')),
            ],
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('electricity_meter', models.CharField(max_length=50)),
                ('water_meter', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.site')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration_months', models.IntegerField()),
                ('end_date', models.DateField(blank=True)),
                ('contract_file', models.FileField(upload_to='contracts/')),
                ('rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rentalunit')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tenant')),
            ],
        ),
    ]
