# Generated by Django 5.1.5 on 2025-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_rentalunit_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(default=1111, max_length=50, verbose_name='المدينة'),
            preserve_default=False,
        ),
    ]
