# Generated by Django 5.1.5 on 2025-01-31 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tenant_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conno', models.CharField(max_length=20)),
                ('nameno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('dateren', models.DateField()),
                ('datestr', models.DateField()),
                ('dateend', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='rental_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.rentalunit'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.site'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.tenant'),
        ),
        migrations.AlterField(
            model_name='rentalunit',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_units', to='main_app.site'),
        ),
    ]
